### ISSUE TITLE
how to flash ?

### ISSUE THREAD

**Issue by beryindo** [toskyRocker/Arduino_Parser_Ublox_Neo_M8N#1]
how to flash ublox m8n??

**Comment by toskyRocker** [comment]
Check my website  http://andrea-toscano.com/u-blox-neo-m8n-u-center-configuration-and-arduino-parser-sketch/

**Comment by beryindo** [comment]
can't open

**Comment by beryindo** [comment]
if I flash, it is no problem ?
https://i.imgur.com/HtBzJUa.jpg

**Comment by toskyRocker** [comment]
I develop that more than 2 years ago . it might be a version issue. Go to
andrea-toscano.com and in the Blog section look for m8n

Il 20 ott 2017 2:43 PM, "beryindo" <notifications@github.com> ha scritto:

**Comment by beryindo** [comment]
I try save and change with manual, but, if device restart, configuration back to default
